### ISSUE TITLE
instructions need updating - ask clone no longer works

### ISSUE THREAD

**Issue by jallwork** [alexa/skill-sample-python-fact-in-skill-purchases#11]
ask clone instruction no longer works.

ASK CLI v2 removes the clone command for cloning an AWS-hosted skill to a local machine.

see: https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-v1-to-v2-migration-guide.html

Please update instructions for CLI v2

**Comment by dievaa** [comment]
Instructions have been updated.
