### ISSUE TITLE
ask add isp Command not recognized. Please run "ask" to check the user instructions.

### ISSUE THREAD

**Issue by Daniyaldehleh** [alexa/skill-sample-python-fact-in-skill-purchases#6]
Hi There,

I cloned my skill --> moved to the root directory and once I inserted "ask add isp" it gave me the following error. Is it updated to something else? what shall i do?

**Comment by kakhaUrigashvili** [comment]
@danieldhz may be this can help https://github.com/alexa/ask-cli/issues/141

**Comment by Daniyaldehleh** [comment]
@kakhaUrigashvili Thank you so much. Also, in the [doc](https://developer.amazon.com/en-US/docs/alexa/in-skill-purchase/use-the-cli-to-manage-in-skill-products.html#products-list-in-a-skill-configuration-file) it says to add the  `"in_skill_products`": to .ask/config.  However, such action hasn't been done in the repo [.ask/config](https://github.com/alexa/skill-sample-python-fact-in-skill-purchases/blob/master/.ask/config). Thus, should we do it or not?
Lastly, is there a simpler way to just check whether a user is _subscribed_ or nor rather than checking through the purchase history of entitled products.

**Comment by kakhaUrigashvili** [comment]
@daltonhuynh I think the docs are referring to ask cli v1. Only command that I can think of is "ask smapi get-isp-summary"  (ask cli v2) but it may be not what you are looking for.

**Comment by Shreyas-vgr** [comment]
> @kakhaUrigashvili Thank you so much. Also, in the [doc](https://developer.amazon.com/en-US/docs/alexa/in-skill-purchase/use-the-cli-to-manage-in-skill-products.html#products-list-in-a-skill-configuration-file) it says to add the `"in_skill_products`": to .ask/config. However, such action hasn't been done in the repo [.ask/config](https://github.com/alexa/skill-sample-python-fact-in-skill-purchases/blob/master/.ask/config). Thus, should we do it or not?

Yes, when you run `ask add isp` and eventually run `ask deploy` from ASK CLI v1, the .ask/config gets updated with in_skill_products you have specified.

> Lastly, is there a simpler way to just check whether a user is subscribed or nor rather than checking through the purchase history of entitled products.

Sorry unfortunately there is no simpler way currently.
